### ISSUE TITLE
Parallel publishing

### ISSUE THREAD

**Issue by om26er** [s-things/wick#76]
We need to support parallel publish of events. @muzzammilshahid we need to first implement `--repeat` for publications

**Comment by oberstet** [comment]
just some quick notes from the sidelines / as I've been doing WAMP benchmarking code before.

"parallel" wording. there also is "concurrent", and in my eyes, the difference is:

"parallel": the number of TCP client-to-router connections opened by the tool to do benchmarks limits the number of e.g. WAMP calls that can be submitted and routed in _parallel_. obviously, a TCP connection in the router that is in the middle of receiving a WAMP CALL message is busy, and since receiving that single WAMP CALL message on a given TCP takes some time, that's the performance wall.

"concurrency": the number of WAMP actions issued (eg a CALL done) but not yet completed (eg a RESULT received) on a single WAMP session (TCP connection) is the other performance wall.

only "parallel" and "concurrency" together complete the controls, and one needs to measure both "throughput" and "latency" (avg/median/q99/max)

in my experience, an ideal tool would allow to

1. measure WAMP action latency and throughput
2. measure minimum latency and maximum throughput
3. measure latency while maximizing (in a limited way) throughput, and measure throughput while minimizing latency (in a limited way, that is a defined maximum latency specified)

and control resources available and used for doing so

1. number of CPU cores (threads/processes) used
2. number of connections (TCP or Unix FDs) used

**Comment by oberstet** [comment]
> INFO[0000] session joined in 1ms                        
> INFO[0000] call took 203ms

fwiw, the numbers suggest that in this particular case the RPC endpoint, the called procedure, is actually doing some real work. 1ms roundtrip for the join, while 200ms for a call ...

**Comment by om26er** [comment]
> > INFO[0000] session joined in 1ms                        
> > INFO[0000] call took 203ms
> 
> fwiw, the numbers suggest that in this particular case the RPC endpoint, the called procedure, is actually doing some real work. 1ms roundtrip for the join, while 200ms for a call ...

yeah, the callee was doing a "sleep 0.2" on its end
